### ISSUE TITLE
Maxime_Eeraerts_Prunus_avium_Belgium_2017_2019

### ISSUE THREAD

**Issue by MaximeEeraerts** [ibartomeus/OBservData#2]
**Describe the dataset**
20-25 sites (some sites were sampled twice of three years
crop: sweet cherry (Prunus avium)
name: Maxime Eeraerts (maxime.eeraerts@gmail.com)
location: Belgium, Europe

**Did you run the tests in `Your_own_data`?**
No, I do not know how to run the test

**URL where we can find the data?**
https://github.com/MaximeEeraerts/Maxime_Eeraerts_Prunus_avium_Belgium_2017_2019

Thanks!

**Comment by AlfonsoAllen** [comment]
Hi Maxime!

Thanks for your contribution! Your dataset has been successfully added to the database. You can check the transposed information [here](https://github.com/ibartomeus/OBservData/tree/master/Final_Data) and [here](https://github.com/ibartomeus/OBservData/tree/master/Processing_files/Datasets_storage). If it is correct, please let us know and we will close this issue.

Thank you very much for participating in this initiative, Maxime!

**Comment by MaximeEeraerts** [comment]
Hello Alfonso
I am not that familiar with github so I think everything is ok.
For my part, nothing more needs to be done?
Greetings
Maxime

Op wo 6 jan. 2021 om 17:35 schreef Alfonso Allen-Perkins <
notifications@github.com>:

**Comment by AlfonsoAllen** [comment]
Hi Maxime.
Please, have a look to the "field_level_data" file that I sent you via email. If its information looks good to you, you don't need to do anything else. If not, just let me know and I will fix the errors. 
Thanks a lot for your attention and help!
Greetings!

**Comment by MaximeEeraerts** [comment]
Hello Alfonso

I have checked these files you sent me yesterday (other email conversation
so I attached them here again to be sure) and everything looks OK.

May I also ask about the submitted draft of this data paper? In what stage
is this process and how will we be informed about the next steps? Is it
also possible to share the submitted draft or not?

Thanks in advance
Greetings
Maxime


Op wo 6 jan. 2021 om 20:43 schreef Alfonso Allen-Perkins <
notifications@github.com>:

**Comment by AlfonsoAllen** [comment]
Hello Maxime.

Thanks for your feedback!

The manuscript that was submitted to Ecology on December 17 is avalaible [here](https://github.com/ibartomeus/OBservData/blob/master/Manuscript/CropPol_data_paper_ESA_V1.pdf). The work is under review from December 22.  If it is accepted, we will try to add your names to the list of co-authors, before publication.

Anyway, we will keep you inform about the paper status via email. If you have any further questions, just let us know.

Best,

Alfonso

**Comment by MaximeEeraerts** [comment]
Thanks for the answer.
It looks like an impressive work, my compliments. I look forward to its
progress.
Have a nice day
Greetings
Maxime

Op do 7 jan. 2021 om 10:41 schreef Alfonso Allen-Perkins <
notifications@github.com>:
