### ISSUE TITLE
[data]

### ISSUE THREAD

**Issue by MaximeEeraerts** [ibartomeus/OBservData#3]
**Describe the dataset**
Sweet cherry, 15 sites, Daniel Ariza
Apple, 15 sites, Daniel Ariza

**Did you run the tests in `Your_own_data`?**
No

**URL where we can find the data?**
https://github.com/MaximeEeraerts/Ariza_etal_SweetCherry_Apple_Belgium_2019

Thanks!

**Comment by AlfonsoAllen** [comment]
After some minor modifications, the dataset was added to the data base.
