### ISSUE TITLE
[data]

### ISSUE THREAD

**Issue by MaximeEeraerts** [ibartomeus/OBservData#6]
16 sites in Washingthon, USA.
Vaccinium corymbosum
Maxime Eearaerts and Lisa Wasko DeVetter
(number of sites, crop, name of the data hokder, ...)

**Did you run the tests in `Your_own_data`?** - NO
(If not, don't worry, we will do it for you)

**URL where we can find the data?**
https://docs.google.com/spreadsheets/d/1oEk-YspNZ8ZPsu1aNffPmBIgrFAhisZJ/edit?usp=sharing&ouid=100710160479172170397&rtpof=true&sd=true

Thanks!

**Comment by ibartomeus** [comment]
Thanks! Updated to v2.1.0!
